//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справочник.
    /// </summary>
    // *** Start programmer edit section *** (IАктуально CustomAttributes)

    // *** End programmer edit section *** (IАктуально CustomAttributes)
    [BusinessServer("IIS.Прокат_велосипедов_2.IАктуальноBS, Прокат_велосипедов_2.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnDeleteFromStorage)]
    public interface IАктуально
    {
        
        // *** Start programmer edit section *** (IАктуально CustomMembers)

        // *** End programmer edit section *** (IАктуально CustomMembers)

        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (Актуально CustomAttributes)

        // *** End programmer edit section *** (Актуально CustomAttributes)
        bool Актуально
        {
            get;
            set;
        }
        
        /// <summary>
        /// ДатаНачалаАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (ДатаНачалаАктуальности CustomAttributes)

        // *** End programmer edit section *** (ДатаНачалаАктуальности CustomAttributes)
        System.DateTime ДатаНачалаАктуальности
        {
            get;
            set;
        }
        
        /// <summary>
        /// ДатаОкончанияАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (ДатаОкончанияАктуальности CustomAttributes)

        // *** End programmer edit section *** (ДатаОкончанияАктуальности CustomAttributes)
        ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончанияАктуальности
        {
            get;
            set;
        }
    }
}
