//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Велосипед в перевозке.
    /// </summary>
    // *** Start programmer edit section *** (ВелосипедВПеревозке CustomAttributes)

    // *** End programmer edit section *** (ВелосипедВПеревозке CustomAttributes)
    [AutoAltered()]
    [Caption("Велосипед в перевозке")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВелосипедВПеревозкеE", new string[] {
            "Велосипед as \'Велосипед\'",
            "Велосипед.Номер as \'Номер\'"}, Hidden=new string[] {
            "Велосипед.Номер"})]
    [MasterViewDefineAttribute("ВелосипедВПеревозкеE", "Велосипед", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    public class ВелосипедВПеревозке : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Прокат_велосипедов_2.Велосипед fВелосипед;
        
        private IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда fПеревозкаВелосипеда;
        
        // *** Start programmer edit section *** (ВелосипедВПеревозке CustomMembers)

        // *** End programmer edit section *** (ВелосипедВПеревозке CustomMembers)

        
        /// <summary>
        /// Велосипед в перевозке.
        /// </summary>
        // *** Start programmer edit section *** (ВелосипедВПеревозке.Велосипед CustomAttributes)

        // *** End programmer edit section *** (ВелосипедВПеревозке.Велосипед CustomAttributes)
        [PropertyStorage(new string[] {
                "Велосипед"})]
        [NotNull()]
        public virtual IIS.Прокат_велосипедов_2.Велосипед Велосипед
        {
            get
            {
                // *** Start programmer edit section *** (ВелосипедВПеревозке.Велосипед Get start)

                // *** End programmer edit section *** (ВелосипедВПеревозке.Велосипед Get start)
                IIS.Прокат_велосипедов_2.Велосипед result = this.fВелосипед;
                // *** Start programmer edit section *** (ВелосипедВПеревозке.Велосипед Get end)

                // *** End programmer edit section *** (ВелосипедВПеревозке.Велосипед Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВелосипедВПеревозке.Велосипед Set start)

                // *** End programmer edit section *** (ВелосипедВПеревозке.Велосипед Set start)
                this.fВелосипед = value;
                // *** Start programmer edit section *** (ВелосипедВПеревозке.Велосипед Set end)

                // *** End programmer edit section *** (ВелосипедВПеревозке.Велосипед Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда.
        /// </summary>
        // *** Start programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда CustomAttributes)

        // *** End programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПеревозкаВелосипеда"})]
        public virtual IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда ПеревозкаВелосипеда
        {
            get
            {
                // *** Start programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Get start)

                // *** End programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Get start)
                IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда result = this.fПеревозкаВелосипеда;
                // *** Start programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Get end)

                // *** End programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Set start)

                // *** End programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Set start)
                this.fПеревозкаВелосипеда = value;
                // *** Start programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Set end)

                // *** End programmer edit section *** (ВелосипедВПеревозке.ПеревозкаВелосипеда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВелосипедВПеревозкеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВелосипедВПеревозкеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВелосипедВПеревозкеE", typeof(IIS.Прокат_велосипедов_2.ВелосипедВПеревозке));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВелосипедВПеревозке.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВелосипедВПеревозке CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВелосипедВПеревозке CustomAttributes)
    public class DetailArrayOfВелосипедВПеревозке : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Прокат_велосипедов_2.DetailArrayOfВелосипедВПеревозке members)

        // *** End programmer edit section *** (IIS.Прокат_велосипедов_2.DetailArrayOfВелосипедВПеревозке members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВелосипедВПеревозке by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВелосипедВПеревозке.
        /// </summary>
        public DetailArrayOfВелосипедВПеревозке(IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда fПеревозкаВелосипеда) : 
                base(typeof(ВелосипедВПеревозке), ((ICSSoft.STORMNET.DataObject)(fПеревозкаВелосипеда)))
        {
        }
        
        public IIS.Прокат_велосипедов_2.ВелосипедВПеревозке this[int index]
        {
            get
            {
                return ((IIS.Прокат_велосипедов_2.ВелосипедВПеревозке)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Прокат_велосипедов_2.ВелосипедВПеревозке dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
