//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// История расценок.
    /// </summary>
    // *** Start programmer edit section *** (ИсторияРасценок CustomAttributes)

    // *** End programmer edit section *** (ИсторияРасценок CustomAttributes)
    [AutoAltered()]
    [Caption("История расценок")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ИсторияРасценокE", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Стоимость as \'Стоимость\'"})]
    public class ИсторияРасценок : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private System.DateTime fДатаНачала;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончания;
        
        private decimal fСтоимость;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private IIS.Прокат_велосипедов_2.ТипВелосипеда fТипВелосипеда;
        
        // *** Start programmer edit section *** (ИсторияРасценок CustomMembers)

        // *** End programmer edit section *** (ИсторияРасценок CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.ДатаНачала CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаНачала Get start)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаНачала Get end)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаНачала Set start)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаНачала Set end)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.ДатаОкончания CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаОкончания Get start)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаОкончания Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаОкончания Get end)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаОкончания Set start)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ИсторияРасценок.ДатаОкончания Set end)

                // *** End programmer edit section *** (ИсторияРасценок.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.Стоимость CustomAttributes)
        [NotNull()]
        public virtual decimal Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.Стоимость Get start)

                // *** End programmer edit section *** (ИсторияРасценок.Стоимость Get start)
                decimal result = this.fСтоимость;
                // *** Start programmer edit section *** (ИсторияРасценок.Стоимость Get end)

                // *** End programmer edit section *** (ИсторияРасценок.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.Стоимость Set start)

                // *** End programmer edit section *** (ИсторияРасценок.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ИсторияРасценок.Стоимость Set end)

                // *** End programmer edit section *** (ИсторияРасценок.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.CreateTime CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.CreateTime Get start)

                // *** End programmer edit section *** (ИсторияРасценок.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (ИсторияРасценок.CreateTime Get end)

                // *** End programmer edit section *** (ИсторияРасценок.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.CreateTime Set start)

                // *** End programmer edit section *** (ИсторияРасценок.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (ИсторияРасценок.CreateTime Set end)

                // *** End programmer edit section *** (ИсторияРасценок.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.Creator CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.Creator Get start)

                // *** End programmer edit section *** (ИсторияРасценок.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (ИсторияРасценок.Creator Get end)

                // *** End programmer edit section *** (ИсторияРасценок.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.Creator Set start)

                // *** End programmer edit section *** (ИсторияРасценок.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (ИсторияРасценок.Creator Set end)

                // *** End programmer edit section *** (ИсторияРасценок.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.EditTime CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.EditTime Get start)

                // *** End programmer edit section *** (ИсторияРасценок.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (ИсторияРасценок.EditTime Get end)

                // *** End programmer edit section *** (ИсторияРасценок.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.EditTime Set start)

                // *** End programmer edit section *** (ИсторияРасценок.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (ИсторияРасценок.EditTime Set end)

                // *** End programmer edit section *** (ИсторияРасценок.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.Editor CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.Editor Get start)

                // *** End programmer edit section *** (ИсторияРасценок.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (ИсторияРасценок.Editor Get end)

                // *** End programmer edit section *** (ИсторияРасценок.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.Editor Set start)

                // *** End programmer edit section *** (ИсторияРасценок.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (ИсторияРасценок.Editor Set end)

                // *** End programmer edit section *** (ИсторияРасценок.Editor Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Прокат_велосипедов_2.ТипВелосипеда.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияРасценок.ТипВелосипеда CustomAttributes)

        // *** End programmer edit section *** (ИсторияРасценок.ТипВелосипеда CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ТипВелосипеда"})]
        public virtual IIS.Прокат_велосипедов_2.ТипВелосипеда ТипВелосипеда
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияРасценок.ТипВелосипеда Get start)

                // *** End programmer edit section *** (ИсторияРасценок.ТипВелосипеда Get start)
                IIS.Прокат_велосипедов_2.ТипВелосипеда result = this.fТипВелосипеда;
                // *** Start programmer edit section *** (ИсторияРасценок.ТипВелосипеда Get end)

                // *** End programmer edit section *** (ИсторияРасценок.ТипВелосипеда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияРасценок.ТипВелосипеда Set start)

                // *** End programmer edit section *** (ИсторияРасценок.ТипВелосипеда Set start)
                this.fТипВелосипеда = value;
                // *** Start programmer edit section *** (ИсторияРасценок.ТипВелосипеда Set end)

                // *** End programmer edit section *** (ИсторияРасценок.ТипВелосипеда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Прокат_велосипедов_2.ИсторияРасценок));
                }
            }
            
            /// <summary>
            /// "ИсторияРасценокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИсторияРасценокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИсторияРасценокE", typeof(IIS.Прокат_велосипедов_2.ИсторияРасценок));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of ИсторияРасценок.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfИсторияРасценок CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfИсторияРасценок CustomAttributes)
    public class DetailArrayOfИсторияРасценок : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Прокат_велосипедов_2.DetailArrayOfИсторияРасценок members)

        // *** End programmer edit section *** (IIS.Прокат_велосипедов_2.DetailArrayOfИсторияРасценок members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ИсторияРасценок by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ИсторияРасценок.
        /// </summary>
        public DetailArrayOfИсторияРасценок(IIS.Прокат_велосипедов_2.ТипВелосипеда fТипВелосипеда) : 
                base(typeof(ИсторияРасценок), ((ICSSoft.STORMNET.DataObject)(fТипВелосипеда)))
        {
        }
        
        public IIS.Прокат_велосипедов_2.ИсторияРасценок this[int index]
        {
            get
            {
                return ((IIS.Прокат_велосипедов_2.ИсторияРасценок)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Прокат_велосипедов_2.ИсторияРасценок dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
