//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// История состояний.
    /// </summary>
    // *** Start programmer edit section *** (ИсторияСостояний CustomAttributes)

    // *** End programmer edit section *** (ИсторияСостояний CustomAttributes)
    [AutoAltered()]
    [Caption("История состояний")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИсторияСостоянийE", new string[] {
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "СостояниеВелосипеда as \'Состояние велосипеда\'",
            "СостояниеВелосипеда.Название as \'Название\'"}, Hidden=new string[] {
            "СостояниеВелосипеда.Название"})]
    [MasterViewDefineAttribute("ИсторияСостоянийE", "СостояниеВелосипеда", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class ИсторияСостояний : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаНачала;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончания;
        
        private IIS.Прокат_велосипедов_2.СостояниеВелосипеда fСостояниеВелосипеда;
        
        private IIS.Прокат_велосипедов_2.Велосипед fВелосипед;
        
        // *** Start programmer edit section *** (ИсторияСостояний CustomMembers)

        // *** End programmer edit section *** (ИсторияСостояний CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияСостояний.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ИсторияСостояний.ДатаНачала CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаНачала Get start)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаНачала Get end)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаНачала Set start)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаНачала Set end)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияСостояний.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ИсторияСостояний.ДатаОкончания CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаОкончания Get start)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаОкончания Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаОкончания Get end)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаОкончания Set start)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ИсторияСостояний.ДатаОкончания Set end)

                // *** End programmer edit section *** (ИсторияСостояний.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// История состояний.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда CustomAttributes)

        // *** End programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда CustomAttributes)
        [PropertyStorage(new string[] {
                "СостояниеВелосипеда"})]
        [NotNull()]
        public virtual IIS.Прокат_велосипедов_2.СостояниеВелосипеда СостояниеВелосипеда
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Get start)

                // *** End programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Get start)
                IIS.Прокат_велосипедов_2.СостояниеВелосипеда result = this.fСостояниеВелосипеда;
                // *** Start programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Get end)

                // *** End programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Set start)

                // *** End programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Set start)
                this.fСостояниеВелосипеда = value;
                // *** Start programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Set end)

                // *** End programmer edit section *** (ИсторияСостояний.СостояниеВелосипеда Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Прокат_велосипедов_2.Велосипед.
        /// </summary>
        // *** Start programmer edit section *** (ИсторияСостояний.Велосипед CustomAttributes)

        // *** End programmer edit section *** (ИсторияСостояний.Велосипед CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Велосипед"})]
        public virtual IIS.Прокат_велосипедов_2.Велосипед Велосипед
        {
            get
            {
                // *** Start programmer edit section *** (ИсторияСостояний.Велосипед Get start)

                // *** End programmer edit section *** (ИсторияСостояний.Велосипед Get start)
                IIS.Прокат_велосипедов_2.Велосипед result = this.fВелосипед;
                // *** Start programmer edit section *** (ИсторияСостояний.Велосипед Get end)

                // *** End programmer edit section *** (ИсторияСостояний.Велосипед Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИсторияСостояний.Велосипед Set start)

                // *** End programmer edit section *** (ИсторияСостояний.Велосипед Set start)
                this.fВелосипед = value;
                // *** Start programmer edit section *** (ИсторияСостояний.Велосипед Set end)

                // *** End programmer edit section *** (ИсторияСостояний.Велосипед Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИсторияСостоянийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИсторияСостоянийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИсторияСостоянийE", typeof(IIS.Прокат_велосипедов_2.ИсторияСостояний));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ИсторияСостояний.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfИсторияСостояний CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfИсторияСостояний CustomAttributes)
    public class DetailArrayOfИсторияСостояний : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Прокат_велосипедов_2.DetailArrayOfИсторияСостояний members)

        // *** End programmer edit section *** (IIS.Прокат_велосипедов_2.DetailArrayOfИсторияСостояний members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ИсторияСостояний by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ИсторияСостояний.
        /// </summary>
        public DetailArrayOfИсторияСостояний(IIS.Прокат_велосипедов_2.Велосипед fВелосипед) : 
                base(typeof(ИсторияСостояний), ((ICSSoft.STORMNET.DataObject)(fВелосипед)))
        {
        }
        
        public IIS.Прокат_велосипедов_2.ИсторияСостояний this[int index]
        {
            get
            {
                return ((IIS.Прокат_велосипедов_2.ИсторияСостояний)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Прокат_велосипедов_2.ИсторияСостояний dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
