//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перевозка велосипеда.
    /// </summary>
    // *** Start programmer edit section *** (ПеревозкаВелосипеда CustomAttributes)

    // *** End programmer edit section *** (ПеревозкаВелосипеда CustomAttributes)
    [AutoAltered()]
    [Caption("Перевозка велосипеда")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПеревозкаВелосипедаE", new string[] {
            "Стоимость as \'Стоимость\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаКонца as \'Дата конца\'",
            "КонечнаяТочка as \'Конечная точка\'",
            "КонечнаяТочка.Адрес as \'Адрес\'",
            "НачальнаяТочка as \'Начальная точка\'",
            "НачальнаяТочка.Адрес as \'Адрес\'",
            "Водитель as \'Водитель\'",
            "Водитель.ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("ПеревозкаВелосипедаE", "ВелосипедВПеревозке", "ВелосипедВПеревозкеE", true, "", "Велосипед в перевозке", true, new string[] {
            ""})]
    [View("ПеревозкаВелосипедаL", new string[] {
            "Стоимость as \'Стоимость\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаКонца as \'Дата конца\'",
            "КонечнаяТочка.Адрес as \'Адрес\'",
            "НачальнаяТочка.Адрес as \'Адрес\'",
            "Водитель.ФИО as \'ФИО\'"})]
    public class ПеревозкаВелосипеда : ICSSoft.STORMNET.DataObject
    {
        
        private decimal fСтоимость;
        
        private System.DateTime fДатаНачала;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаКонца;
        
        private IIS.Прокат_велосипедов_2.ТочкаПроката fКонечнаяТочка;
        
        private IIS.Прокат_велосипедов_2.ТочкаПроката fНачальнаяТочка;
        
        private IIS.Прокат_велосипедов_2.Сотрудник fВодитель;
        
        private IIS.Прокат_велосипедов_2.DetailArrayOfВелосипедВПеревозке fВелосипедВПеревозке;
        
        // *** Start programmer edit section *** (ПеревозкаВелосипеда CustomMembers)

        // *** End programmer edit section *** (ПеревозкаВелосипеда CustomMembers)

        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.Стоимость CustomAttributes)
        [NotNull()]
        public virtual decimal Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Стоимость Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Стоимость Get start)
                decimal result = this.fСтоимость;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Стоимость Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Стоимость Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Стоимость Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаКонца.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаКонца
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаКонца;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Set start)
                this.fДатаКонца = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ДатаКонца Set end)
            }
        }
        
        /// <summary>
        /// Перевозка велосипеда.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка CustomAttributes)
        [NotNull()]
        public virtual IIS.Прокат_велосипедов_2.ТочкаПроката КонечнаяТочка
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Get start)
                IIS.Прокат_велосипедов_2.ТочкаПроката result = this.fКонечнаяТочка;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Set start)
                this.fКонечнаяТочка = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.КонечнаяТочка Set end)
            }
        }
        
        /// <summary>
        /// Перевозка велосипеда.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка CustomAttributes)
        [NotNull()]
        public virtual IIS.Прокат_велосипедов_2.ТочкаПроката НачальнаяТочка
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Get start)
                IIS.Прокат_велосипедов_2.ТочкаПроката result = this.fНачальнаяТочка;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Set start)
                this.fНачальнаяТочка = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.НачальнаяТочка Set end)
            }
        }
        
        /// <summary>
        /// Перевозка велосипеда.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.Водитель CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.Водитель CustomAttributes)
        [NotNull()]
        public virtual IIS.Прокат_велосипедов_2.Сотрудник Водитель
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Водитель Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Водитель Get start)
                IIS.Прокат_велосипедов_2.Сотрудник result = this.fВодитель;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Водитель Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Водитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Водитель Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Водитель Set start)
                this.fВодитель = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.Водитель Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.Водитель Set end)
            }
        }
        
        /// <summary>
        /// Перевозка велосипеда.
        /// </summary>
        // *** Start programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке CustomAttributes)

        // *** End programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке CustomAttributes)
        public virtual IIS.Прокат_велосипедов_2.DetailArrayOfВелосипедВПеревозке ВелосипедВПеревозке
        {
            get
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Get start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Get start)
                if ((this.fВелосипедВПеревозке == null))
                {
                    this.fВелосипедВПеревозке = new IIS.Прокат_велосипедов_2.DetailArrayOfВелосипедВПеревозке(this);
                }
                IIS.Прокат_велосипедов_2.DetailArrayOfВелосипедВПеревозке result = this.fВелосипедВПеревозке;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Get end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Set start)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Set start)
                this.fВелосипедВПеревозке = value;
                // *** Start programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Set end)

                // *** End programmer edit section *** (ПеревозкаВелосипеда.ВелосипедВПеревозке Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПеревозкаВелосипедаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПеревозкаВелосипедаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПеревозкаВелосипедаE", typeof(IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда));
                }
            }
            
            /// <summary>
            /// "ПеревозкаВелосипедаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПеревозкаВелосипедаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПеревозкаВелосипедаL", typeof(IIS.Прокат_велосипедов_2.ПеревозкаВелосипеда));
                }
            }
        }
    }
}
