//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "ФИО as \'ФИО\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    [View("СотрудникE", new string[] {
            "ФИО as \'ФИО\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    [View("СотрудникL", new string[] {
            "ФИО as \'ФИО\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject, IIS.Прокат_велосипедов_2.IАктуально, IDataObjectWithAuditFields
    {
        
        private string fФИО;
        
        private bool fАктуально;
        
        private System.DateTime fДатаНачалаАктуальности;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончанияАктуальности;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Get start)

                // *** End programmer edit section *** (Сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудник.ФИО Get end)

                // *** End programmer edit section *** (Сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ФИО Set start)

                // *** End programmer edit section *** (Сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудник.ФИО Set end)

                // *** End programmer edit section *** (Сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Актуально CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Актуально Get start)

                // *** End programmer edit section *** (Сотрудник.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (Сотрудник.Актуально Get end)

                // *** End programmer edit section *** (Сотрудник.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Актуально Set start)

                // *** End programmer edit section *** (Сотрудник.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (Сотрудник.Актуально Set end)

                // *** End programmer edit section *** (Сотрудник.Актуально Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачалаАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ДатаНачалаАктуальности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ДатаНачалаАктуальности CustomAttributes)
        public virtual System.DateTime ДатаНачалаАктуальности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Get start)

                // *** End programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Get start)
                System.DateTime result = this.fДатаНачалаАктуальности;
                // *** Start programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Get end)

                // *** End programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Set start)

                // *** End programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Set start)
                this.fДатаНачалаАктуальности = value;
                // *** Start programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Set end)

                // *** End programmer edit section *** (Сотрудник.ДатаНачалаАктуальности Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончанияАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончанияАктуальности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Get start)

                // *** End programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончанияАктуальности;
                // *** Start programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Get end)

                // *** End programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Set start)

                // *** End programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Set start)
                this.fДатаОкончанияАктуальности = value;
                // *** Start programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Set end)

                // *** End programmer edit section *** (Сотрудник.ДатаОкончанияАктуальности Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.CreateTime Get start)

                // *** End programmer edit section *** (Сотрудник.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Сотрудник.CreateTime Get end)

                // *** End programmer edit section *** (Сотрудник.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.CreateTime Set start)

                // *** End programmer edit section *** (Сотрудник.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Сотрудник.CreateTime Set end)

                // *** End programmer edit section *** (Сотрудник.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Creator CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Creator Get start)

                // *** End programmer edit section *** (Сотрудник.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Сотрудник.Creator Get end)

                // *** End programmer edit section *** (Сотрудник.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Creator Set start)

                // *** End programmer edit section *** (Сотрудник.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Сотрудник.Creator Set end)

                // *** End programmer edit section *** (Сотрудник.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.EditTime CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.EditTime Get start)

                // *** End programmer edit section *** (Сотрудник.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Сотрудник.EditTime Get end)

                // *** End programmer edit section *** (Сотрудник.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.EditTime Set start)

                // *** End programmer edit section *** (Сотрудник.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Сотрудник.EditTime Set end)

                // *** End programmer edit section *** (Сотрудник.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Editor CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Editor Get start)

                // *** End programmer edit section *** (Сотрудник.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Сотрудник.Editor Get end)

                // *** End programmer edit section *** (Сотрудник.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Editor Set start)

                // *** End programmer edit section *** (Сотрудник.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Сотрудник.Editor Set end)

                // *** End programmer edit section *** (Сотрудник.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Прокат_велосипедов_2.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.Прокат_велосипедов_2.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.Прокат_велосипедов_2.Сотрудник));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
