//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние велосипеда.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеВелосипеда CustomAttributes)

    // *** End programmer edit section *** (СостояниеВелосипеда CustomAttributes)
    [AutoAltered()]
    [Caption("Состояние велосипеда")]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Название as \'Название\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    [View("СостояниеВелосипедаE", new string[] {
            "Название as \'Название\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    [View("СостояниеВелосипедаL", new string[] {
            "Название as \'Название\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    public class СостояниеВелосипеда : ICSSoft.STORMNET.DataObject, IIS.Прокат_велосипедов_2.IАктуально, IDataObjectWithAuditFields
    {
        
        private string fНазвание;
        
        private bool fАктуально;
        
        private System.DateTime fДатаНачалаАктуальности;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончанияАктуальности;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (СостояниеВелосипеда CustomMembers)

        // *** End programmer edit section *** (СостояниеВелосипеда CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.Название CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачалаАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности CustomAttributes)
        public virtual System.DateTime ДатаНачалаАктуальности
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get start)
                System.DateTime result = this.fДатаНачалаАктуальности;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set start)
                this.fДатаНачалаАктуальности = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончанияАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончанияАктуальности
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончанияАктуальности;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set start)
                this.fДатаОкончанияАктуальности = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.CreateTime CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.CreateTime Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (СостояниеВелосипеда.CreateTime Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.CreateTime Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.CreateTime Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.Creator CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Creator Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Creator Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Creator Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Creator Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.EditTime CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.EditTime Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (СостояниеВелосипеда.EditTime Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.EditTime Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.EditTime Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.Editor CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Editor Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Editor Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Editor Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Editor Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Прокат_велосипедов_2.СостояниеВелосипеда));
                }
            }
            
            /// <summary>
            /// "СостояниеВелосипедаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостояниеВелосипедаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостояниеВелосипедаE", typeof(IIS.Прокат_велосипедов_2.СостояниеВелосипеда));
                }
            }
            
            /// <summary>
            /// "СостояниеВелосипедаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостояниеВелосипедаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостояниеВелосипедаL", typeof(IIS.Прокат_велосипедов_2.СостояниеВелосипеда));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
