//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние велосипеда.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеВелосипеда CustomAttributes)

    // *** End programmer edit section *** (СостояниеВелосипеда CustomAttributes)
    [AutoAltered()]
    [Caption("Состояние велосипеда")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СостояниеВелосипедаE", new string[] {
            "Название as \'Название\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    [View("СостояниеВелосипедаL", new string[] {
            "Название as \'Название\'",
            "Актуально as \'Актуально\'",
            "ДатаНачалаАктуальности as \'Дата начала актуальности\'",
            "ДатаОкончанияАктуальности as \'Дата окончания актуальности\'"})]
    public class СостояниеВелосипеда : ICSSoft.STORMNET.DataObject, IIS.Прокат_велосипедов_2.IАктуально
    {
        
        private string fНазвание;
        
        private bool fАктуально;
        
        private System.DateTime fДатаНачалаАктуальности;
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDateTime fДатаОкончанияАктуальности;
        
        // *** Start programmer edit section *** (СостояниеВелосипеда CustomMembers)

        // *** End programmer edit section *** (СостояниеВелосипеда CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.Название CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Название Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Название Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.Актуально Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.Актуально Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачалаАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности CustomAttributes)
        public virtual System.DateTime ДатаНачалаАктуальности
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get start)
                System.DateTime result = this.fДатаНачалаАктуальности;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set start)
                this.fДатаНачалаАктуальности = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаНачалаАктуальности Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончанияАктуальности.
        /// </summary>
        // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности CustomAttributes)

        // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности CustomAttributes)
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDateTime ДатаОкончанияАктуальности
        {
            get
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDateTime result = this.fДатаОкончанияАктуальности;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set start)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set start)
                this.fДатаОкончанияАктуальности = value;
                // *** Start programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set end)

                // *** End programmer edit section *** (СостояниеВелосипеда.ДатаОкончанияАктуальности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СостояниеВелосипедаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостояниеВелосипедаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостояниеВелосипедаE", typeof(IIS.Прокат_велосипедов_2.СостояниеВелосипеда));
                }
            }
            
            /// <summary>
            /// "СостояниеВелосипедаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостояниеВелосипедаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостояниеВелосипедаL", typeof(IIS.Прокат_велосипедов_2.СостояниеВелосипеда));
                }
            }
        }
    }
}
