/*flexberryautogenerated="false"*/

namespace IIS.Прокат_велосипедов_2
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.Web.AjaxControls;
    using ICSSoft.STORMNET.Business;
    using System.Web.Services;
    using System;
    using IIS.University.Tools;
    using System.Text;

    public partial class ВыдачаВелосипедаE : BaseEditForm<ВыдачаВелосипеда>
    {
        /// <summary>
        /// Конструктор формы.
        /// </summary>
        public ВыдачаВелосипедаE()
            : base(ВыдачаВелосипеда.Views.ВыдачаВелосипедаE)
        {
            
        }

        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/VydachaVelosipeda/VydachaVelosipedaE.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            bool hasRights = RightManager.AccessCheck("Выдать велосипед");
            if (!hasRights)
            {
                throw new Exception("У вас нет прав для выполнения этой операции");
            }
        }

        /// <summary>
        /// Здесь лучше всего писать бизнес-логику, оперируя только объектом данных.
        /// </summary>
        protected override void PreApplyToControls()
        {
            
        }

        /// <summary>
        /// Здесь лучше всего изменять свойства контролов на странице,
        /// которые не обрабатываются WebBinder.
        /// </summary>
        protected override void PostApplyToControls()
        {
            
            Page.Validate();
            ctrlДатаНачала.ReadOnly = true;
            
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
            //ctrlКлиент.LookUpFormURL = ResolveUrl("/forms/Klient/KlientL.aspx");
            //ctrlКлиент.LookUpFormMenubar = BaseMasterEditorLookUp.YesNo.Yes;
            //ctrlКлиент.LookUpFormToolbar = BaseMasterEditorLookUp.YesNo.Yes;

        }

        /// <summary>
        /// Валидация объекта для сохранения.
        /// </summary>
        /// <returns>true - продолжать сохранение, иначе - прекратить.</returns>
        protected override bool PreSaveObject()
        {
            return base.PreSaveObject();
        }

        /// <summary>
        /// Нетривиальная логика сохранения объекта.
        /// </summary>
        /// <returns>Объект данных, который сохранился.</returns>
        protected override DataObject SaveObject()
        {
            
            

            return DataObject;
        }
        [WebMethod]
        public static string MySaveObject
            (string startDate ,string plannedDuration, string plannedPrice,
             string startPoint, string vel, string klient, string employee)
        {
            StringBuilder errorMessageBuilder = new StringBuilder();
             try
            {
                //Проверка входных парамтеров
                DateTime checkedStartDate = new DateTime();
                if (!DateTime.TryParse(startDate, out checkedStartDate))
                {
                    errorMessageBuilder.Append("Дата начала неправильная. ");
                }

                int checkedPlannedDuration = 0;
                if (!Int32.TryParse(plannedDuration, out checkedPlannedDuration))
                {
                    errorMessageBuilder.Append("Планируемое время неправильное. ");
                }

                decimal checkedPlannedPrice = 0;
                if (!decimal.TryParse(plannedPrice, out checkedPlannedPrice))
                {
                    errorMessageBuilder.Append("Планируемая стоимость неправильная. ");
                }

                Guid checkedStartPoint = new Guid();
                if (!Guid.TryParse(startPoint, out checkedStartPoint))
                {
                    errorMessageBuilder.Append("Точка выдачи неправильная. ");
                }


                Guid checkedVel= new Guid();
                if (!Guid.TryParse(vel, out checkedVel))
                {
                    errorMessageBuilder.Append("Велосипед неправильный. ");
                }


                Guid checkedKlient= new Guid();
                if (!Guid.TryParse(klient, out checkedKlient))
                {
                    errorMessageBuilder.Append("Клиент неправильный. ");
                }

                Guid checkedEmployee= new Guid();
                if (!Guid.TryParse(employee, out checkedEmployee))
                {
                    errorMessageBuilder.Append("Прокатчик неправильный. ");
                }

                if (errorMessageBuilder.Length != 0)
                {
                    throw new Exception(errorMessageBuilder.ToString());
                }

                //Заполнение объекта для сохранения.
                
                var storedObject = new IIS.Прокат_велосипедов_2.ПрокатВелосипеда
                {
                    ДатаНачала = checkedStartDate,
                    Велосипед = PKHelper.CreateDataObject<Велосипед>(checkedVel),
                    ПлановаяСтоимость = checkedPlannedPrice,
                    ПлановаяДлительность = checkedPlannedDuration,
                    ТочкаВыдачи = PKHelper.CreateDataObject<ТочкаПроката>(checkedStartPoint),
                    ТочкаСдачи = null,
                    Прокатчик = PKHelper.CreateDataObject<Сотрудник>(checkedEmployee),
                    Клиент = PKHelper.CreateDataObject<Клиент>(klient),
                    ФактическаяДатаСдачи = null,
                    ФактическаяСтоимость = 0
                };

                //Сохранение и прочее
                var ds = DataServiceProvider.DataService;
                ds.UpdateObject(storedObject);
                var loadedVel = new Велосипед { __PrimaryKey = checkedVel };
                ds.LoadObject(loadedVel);
                string uLogin = ICSSoft.Services.CurrentUserService.CurrentUser.Login;
                LogService.LogInfo($"Пользователь {uLogin} совершил выдачу велосипеда {loadedVel.Номер.ToString()} ");

                return "1";
            }
            catch (System.Exception e )
            {
                return e.Message;
            }

        }
        
        
    }
}