/*flexberryautogenerated="false"*/

namespace IIS.Прокат_велосипедов_2
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.Web.AjaxControls;
    using ICSSoft.STORMNET.Business;
    using System.Web.Services;

    public partial class ВыдачаВелосипедаE : BaseEditForm<ВыдачаВелосипеда>
    {
        /// <summary>
        /// Конструктор формы.
        /// </summary>
        public ВыдачаВелосипедаE()
            : base(ВыдачаВелосипеда.Views.ВыдачаВелосипедаE)
        {
            
        }

        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/VydachaVelosipeda/VydachaVelosipedaE.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Здесь лучше всего писать бизнес-логику, оперируя только объектом данных.
        /// </summary>
        protected override void PreApplyToControls()
        {
            
        }

        /// <summary>
        /// Здесь лучше всего изменять свойства контролов на странице,
        /// которые не обрабатываются WebBinder.
        /// </summary>
        protected override void PostApplyToControls()
        {
            
            Page.Validate();
            
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
            SaveBtn.OnClientClick = "mySaveBtnClickHaandler";
            
        }

        /// <summary>
        /// Валидация объекта для сохранения.
        /// </summary>
        /// <returns>true - продолжать сохранение, иначе - прекратить.</returns>
        protected override bool PreSaveObject()
        {
            return base.PreSaveObject();
        }

        /// <summary>
        /// Нетривиальная логика сохранения объекта.
        /// </summary>
        /// <returns>Объект данных, который сохранился.</returns>
        [WebMethod]
        protected override DataObject SaveObject()
        {
            
            var storedObject = new IIS.Прокат_велосипедов_2.ПрокатВелосипеда
            {
                ДатаНачала = DataObject.ДатаНачала,
                Велосипед = DataObject.Велосипед,
                ПлановаяСтоимость = DataObject.ПлановаяСтоимость,
                ПлановаяДлительность = DataObject.ПлановаяДлительность,
                ТочкаВыдачи = DataObject.ТочкаВыдачи,
                ТочкаСдачи = null,
                Прокатчик = DataObject.Прокатчик,
                Клиент = DataObject.Клиент,
                ФактическаяДатаСдачи = null,
                ФактическаяСтоимость = 0
            };
               
            var ds = DataServiceProvider.DataService;
            ds.UpdateObject(storedObject);

            return DataObject;
        }
        
        
    }
}