<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Spravochniki.aspx.cs" Inherits="IIS.Прокат_велосипедов_2.Справочники" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>
        Справочники
    </h1>
    <div class="main">
        <div class ="listBlock">
            <p class="listTitle">Велосипеды</p>
            <ul>
                <li><a href="SostoyanieVelosipeda/SostoyanieVelosipedaL.aspx">Состояния велосипедов</a></li>
                <li><a href="TipVelosipeda/TipVelosipedaL.aspx">Типы велосипедов</a></li>
            </ul>
        </div>
        <div class="listBlock">
            <p class="listTitle">Люди</p>
            <ul>
                <li> <a href="Klient/KlientL.aspx">Клиенты</a></li>
                <li><a href="Sotrudnik/SotrudnikL.aspx">Сотрудники</a></li>
            </ul>
        </div>
        <div class="listBlock">
            <p class="listTitle">Прокат</p>
            <ul>
                <li><a href="TochkaProkata/TochkaProkataL.aspx">Точки проката</a></li>
            </ul>
        </div>
    </div>
    <style>
        li{display:block}
        .listBlock {
            border-top: 2px solid lightgrey;
            position: relative;
            display: inline-block;
            width: 40%;
            height: 200px;
            padding-top: 10px;
            padding-left: 10px;
            margin-left: 10px;
        }
        .listTitle {
            font-size: 14px;
        }
        li a {
            text-decoration: none;
            color: cornflowerblue;
        }
        ul{
            padding-left:0px;
        }
        .listItem a:hover{
            text-decoration:underline;
            color: cornflowerblue;
        }
        h1{
            margin-left: 21px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
