/*flexberryautogenerated="false"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;
using System.Linq;
using System.Collections.Generic;
using ICSSoft.STORMNET;

namespace IIS.Прокат_велосипедов_2
{
    public partial class Запросы : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected override void OnLoad(EventArgs e)
        {
            var ds = DataServiceProvider.DataService;
            var bikes = ds.Query<Велосипед>();
            var rents = ds.Query<ПрокатВелосипеда>();
            var types = ds.Query<ТипВелосипеда>().ToList();
            
            var typesUsageCounts =
                   types
                  .Select(t => new
                  {
                      num = rents
                            .Where(x => x.Велосипед != null 
                                        && x.Велосипед.ТипВелосипеда !=null 
                                        && x.Велосипед.ТипВелосипеда.__PrimaryKey == t.__PrimaryKey)
                            .Count(),
                      type = t
                  });
          
            var topId = typesUsageCounts
                                .OrderByDescending(x => x.num)
                                .Select(x=>x.type)
                                .FirstOrDefault()
                                .__PrimaryKey;
            var botId = typesUsageCounts
                                .OrderBy(x => x.num)
                                .Select(x=>x.type)
                                .FirstOrDefault()
                                .__PrimaryKey;
            var topType = new ТипВелосипеда { __PrimaryKey = topId };
            var botType = new ТипВелосипеда { __PrimaryKey = botId };
            ds.LoadObject(topType);
            ds.LoadObject(botType);

            mostPop.InnerHtml = topType.Название;
            leastPop.InnerHtml = botType.Название;
            
        }
    }
}
