<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zaprosy.aspx.cs" Inherits="IIS.Прокат_велосипедов_2.Запросы" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Запросы</h1>
    <div class="main">
        <div class="requestBlock">
            <p class ="header">1)Какой тип велосипедов пользуется наибольшей популярностью, а какой наименьшей?</p>
            <p> 
                Наибольшая популярность у <b class="res" id="mostPop" runat="server"></b>
            </p>
            <p>
                Наименьшая популярность у <b class="res" id="leastPop" runat="server"></b>
            </p>
        </div>

    </div>
    <%--1)	Какой тип велосипедов пользуется наибольшей популярностью, а какой наименьшей?
    2)	Какую прибыль приносит каждая из точек проката?
    3)	Сколько велосипедов было испорчено или украдено за месяц?
    4)	Сколько велосипедов было перевезено между точками на специальном автомобиле для балансировки?
    5)	Какова средняя продолжительность проката велосипеда?--%>

</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
