//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Прокат_велосипедов_2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.UserDataTypes;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПриемВелосипедаBS.
    /// </summary>
    // *** Start programmer edit section *** (ПриемВелосипедаBS CustomAttributes)

    // *** End programmer edit section *** (ПриемВелосипедаBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ПриемВелосипедаBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ПриемВелосипедаBS CustomMembers)
        
        // *** End programmer edit section *** (ПриемВелосипедаBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateПриемВелосипеда CustomAttributes)

        // *** End programmer edit section *** (OnUpdateПриемВелосипеда CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateПриемВелосипеда(IIS.Прокат_велосипедов_2.ПриемВелосипеда UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateПриемВелосипеда)
            if (((DataObject)UpdatedObject).GetStatus() == ObjectStatus.Created)
            {
                var storedObject = UpdatedObject.ПрокатВелосипеда;

                storedObject.ФактическаяДатаСдачи = (NullableDateTime)UpdatedObject.ДатаПриема;
                storedObject.ФактическаяСтоимость = UpdatedObject.ФактическаяСтоимость;
                storedObject.Прокатчик = UpdatedObject.Прокатчик;

                storedObject.SetStatus(ObjectStatus.Altered);
                ((DataObject)UpdatedObject).SetStatus(ObjectStatus.UnAltered);
               
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateПриемВелосипеда)
        }
    }
}
