/*flexberryautogenerated="true"*/
namespace IIS.Прокат_велосипедов_2
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class КлиентL : BaseListForm<Клиент>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public КлиентL() : base(Клиент.Views.КлиентL)
        {
            EditPage = КлиентE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Klient/KlientL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
